version: '2'

volumes:
  redis:

networks:
  kbot:
    driver: bridge

services:
  # Redis
  redis:
    image: 'redis/redis-stack:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - kbot
